//
//  UIColor+SBAdditions.h
//
//  Generated by Zeplin on 3/30/17.
//  Copyright (c) 2017 __MyCompanyName__. All rights reserved. 
//

#import <UIKit/UIKit.h>

@interface UIColor (SBAdditions)

+ (UIColor *)sb_soobookBlueColor;
+ (UIColor *)sb_steelColor;
+ (UIColor *)sb_brownBlackColor;
+ (UIColor *)sb_whiteColor;
+ (UIColor *)sb_grayForGradColor;

@end
