//
//  UIColor+SBAdditions.m
//
//  Generated by Zeplin on 3/30/17.
//  Copyright (c) 2017 __MyCompanyName__. All rights reserved. 
//

#import "UIColor+SBAdditions.h"

@implementation UIColor (SBAdditions)

+ (UIColor *)sb_soobookBlueColor {
	return [UIColor colorWithRed:25.0f / 255.0f green:142.0f / 255.0f blue:167.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)sb_steelColor {
	return [UIColor colorWithRed:142.0f / 255.0f green:142.0f / 255.0f blue:147.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)sb_brownBlackColor {
	return [UIColor colorWithWhite:74.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)sb_whiteColor {
	return [UIColor colorWithWhite:255.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)sb_grayForGradColor {
	return [UIColor colorWithWhite:217.0f / 255.0f alpha:1.0f];
}

@end
